# Apple iTunes Music Analysis

In [1]:
import pandas as pd

Import Datasets

In [2]:
df_album = pd.read_csv('album.csv')
df_album.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   album_id   347 non-null    int64
 1   title      347 non-null    object
 2   artist_id  347 non-null    int64
dtypes: int64(2), object(1)
memory usage: 8.3+ KB

In [3]:
df_album.head()

   album_id                                              title  artist_id
0       156                                And Justice For All         50
1       208                               Black Light Syndrome        136
2       257  20th Century Masters - The Millennium Collecti...        179
3       296                      A Copland Celebration, Vol. I        230
4        94                         A Matter of Life and Death         90

LOAD DATASET ARTIST

In [4]:
df_artist = pd.read_csv('artist.csv')
df_artist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   artist_id  275 non-null    int64
 1   name       275 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.4+ KB

In [5]:
df_artist.head()

   artist_id               name
0          1              AC/DC
1          2             Accept
2          3          Aerosmith
3          4  Alanis Morissette
4          5    Alice In Chains

Dataset Customer

In [6]:
df_customer = pd.read_csv('customer.csv')
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     59 non-null     int64
 1   first_name      59 non-null     object
 2   last_name       59 non-null     object
 3   company         10 non-null     object
 4   address         59 non-null     object
 5   city            59 non-null     object
 6   state           30 non-null     object
 7   country         59 non-null     object
 8   postal_code     55 non-null     object
 9   phone           58 non-null     object
 10  fax             12 non-null     object
 11  email           59 non-null     object
 12  support_rep_id  59 non-null     int64
dtypes: int64(2), object(11)
memory usage: 6.1+ KB

In [7]:
df_customer.head()

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

Load Dataset Employee

In [8]:
df_employee = pd.read_csv('employee.csv')
df_employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  9 non-null      int64
 1   last_name    9 non-null      object
 2   first_name   9 non-null      object
 3   title        9 non-null      object
 4   reports_to   8 non-null      float64
 5   levels       9 non-null      object
 6   birthdate    9 non-null      object
 7   hire_date    9 non-null      object
 8   address      9 non-null      object
 9   city         9 non-null      object
 10  state        9 non-null      object
 11  country      9 non-null      object
 12  postal_code  9 non-null      object
 13  phone        9 non-null      object
 14  fax          9 non-null      object
 15  email        9 non-null      object
dtypes: float64(1), int64(1), object(14)
memory usage: 1.3+ KB

In [9]:
df_employee.head(8)

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,9.0,L6,18-02-1962 00:00,14-08-2016 00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,L4,08-12-1958 00:00,01-05-2016 00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,L1,29-08-1973 00:00,01-04-2017 00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,L1,19-09-1947 00:00,03-05-2017 00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,L1,03-03-1965 00:00,17-10-2017 00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,L3,01-07-1973 00:00,17-10-2016 00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,L2,29-05-1970 00:00,02-01-2017 00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,L2,09-01-1968 00:00,04-03-2017 00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

Load dataset Genre

In [10]:
df_genre = pd.read_csv('genre.csv')
df_genre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genre_id  25 non-null     int64
 1   name      25 non-null     object
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [12]:
df_genre.head(8)

   genre_id                name
0         1                Rock
1         2                Jazz
2         3               Metal
3         4  Alternative & Punk
4         5       Rock And Roll
5         6               Blues
6         7               Latin
7         8              Reggae

LOAD DATASET INVOICE LINE

In [13]:
df_invoiceline = pd.read_csv('invoice_line.csv')
df_invoiceline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4757 entries, 0 to 4756
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   invoice_line_id  4757 non-null   int64
 1   invoice_id       4757 non-null   int64
 2   track_id         4757 non-null   int64
 3   unit_price       4757 non-null   float64
 4   quantity         4757 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 185.9 KB

In [14]:
df_invoiceline.head()

   invoice_line_id  invoice_id  track_id  unit_price  quantity
0                1           1      1158        0.99         1
1                2           1      1159        0.99         1
2                3           1      1160        0.99         1
3                4           1      1161        0.99         1
4                5           1      1162        0.99         1

Load dataset Invoice

In [15]:
df_invoice = pd.read_csv('invoice.csv')
df_invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   invoice_id           614 non-null    int64
 1   customer_id          614 non-null    int64
 2   invoice_date         614 non-null    object
 3   billing_address      614 non-null    object
 4   billing_city         614 non-null    object
 5   billing_state        310 non-null    object
 6   billing_country      614 non-null    object
 7   billing_postal_code  559 non-null    object
 8   total                614 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 43.3+ KB

In [17]:
df_invoice.head(10)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84
1,2,30,2017-01-03 00:00:00,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,9.90
2,3,40,2017-01-05 00:00:00,"8, Rue Hanovre",Paris,NaN,France,75002,1.98
3,4,18,2017-01-06 00:00:00,627 Broadway,New York,NY,USA,10012-2612,7.92
4,5,27,2017-01-07 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,16.83
5,6,31,2017-01-10 00:00:00,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,1.98
6,7,49,2017-01-12 00:00:00,Ordynacka 10,Warsaw,NaN,Poland,00-358,10.89
7,8,59,2017-01-13 00:00:00,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,9.90
8,9,18,2017-01-18 00:00:00,627 Broadway,New York,NY,USA,10012-2612,8.91
9,10,31,2017-01-18 00:00:00,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,1.98

In [18]:
df_mediaType = pd.read_csv('media_type.csv')
df_mediaType.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   media_type_id  5 non-null      int64
 1   name           5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [21]:
df_mediaType.head()

   media_type_id                         name
0              1              MPEG audio file
1              2     Protected AAC audio file
2              3  Protected MPEG-4 video file
3              4     Purchased AAC audio file
4              5               AAC audio file

Load dataset Playlist Track

In [22]:
df_PlaylistTrack    = pd.read_csv('playlist_track.csv')
df_PlaylistTrack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8715 entries, 0 to 8714
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   playlist_id  8715 non-null   int64
 1   track_id     8715 non-null   int64
dtypes: int64(2)
memory usage: 136.3 KB

In [23]:
df_PlaylistTrack.head()

   playlist_id  track_id
0            1      3402
1            1      3389
2            1      3390
3            1      3391
4            1      3392

Load dataset Playlist

In [24]:
df_playlist = pd.read_csv('playlist.csv')
df_playlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   playlist_id  18 non-null     int64
 1   name         18 non-null     object
dtypes: int64(1), object(1)
memory usage: 420.0+ bytes

In [26]:
df_playlist.head(10)

   playlist_id          name
0            1         Music
1            2        Movies
2            3      TV Shows
3            4    Audiobooks
4            5    90’s Music
5            6    Audiobooks
6            7        Movies
7            8         Music
8            9  Music Videos
9           10      TV Shows

Load dataset track

In [27]:
df_track = pd.read_csv('track.csv')
df_track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3503 entries, 0 to 3502
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   track_id       3503 non-null   int64
 1   name           3503 non-null   object
 2   album_id       3503 non-null   int64
 3   media_type_id  3503 non-null   int64
 4   genre_id       3503 non-null   int64
 5   composer       2525 non-null   object
 6   milliseconds   3503 non-null   int64
 7   bytes          3503 non-null   int64
 8   unit_price     3503 non-null   float64
dtypes: float64(1), int64(6), object(2)
memory usage: 246.4+ KB

In [29]:
df_track.head(10)

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,NaN,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99